name: aptafind
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - openpyxl
  - pandas
  - pdfplumber
  - poppler
  - pytorch
  - pypdf
  - pyyaml
  - rapidfuzz
  - rdkit
  - pytest
